version: "3.9"  # optional since v1.27.0
services:
  app:
    build:
        context: .
    ports:
      - "5000:5000"
    volumes:
      - ./app:/app
    command: >
        sh -C "python manage.py runserver 0.0.0.0:8000"
